### ISSUE TITLE
What is needed to go to v1.63

### ISSUE THREAD

**Issue by ThisDrunkDane** [sonoro1234/cimgui#2]

**Comment by sonoro1234** [comment]
Just updating imgui to the point you are interested:

https://github.com/sonoro1234/cimgui#auto-binding-generation

In the repo binding I am wating till 1.63 is released (not WIP)

**Comment by ThisDrunkDane** [comment]
But it is released? https://github.com/ocornut/imgui/releases/tag/v1.63

**Comment by sonoro1234** [comment]
Just updated

**Comment by ThisDrunkDane** [comment]
I know you just updated, but https://github.com/ocornut/imgui/releases/tag/v1.64 was just released xD it's supposed to be 100% functionally different but things have moved, that might play into the generator?

**Comment by sonoro1234** [comment]
It will not affect generator because it just uses imgui.h.
It will change the building of 1.64
