### ISSUE TITLE
Wrong #include path in repo root

### ISSUE THREAD

**Issue by ThisDrunkDane** [sonoro1234/cimgui#3]
When the cimgui_auto.cpp/.h are copied out to the repo root they contain the wrong include path https://github.com/sonoro1234/cimgui/blob/latest_cimgui_auto/cimgui_auto.cpp#L2.

I don't use the cmake build way as it generates a dll on Windows which I don't want. I instead just submodule this repo and compile it myself. However that requires me to make changes to the repo which I would rather avoid.

**Comment by sonoro1234** [comment]
Just corrected
