### ISSUE TITLE
Wrong declaration of functions without arguments

### ISSUE THREAD

**Issue by AlexAltea** [sonoro1234/cimgui#4]
Functions that do not take arguments are being generated as:
```c
CIMGUI_API ImGuiContext* igGetCurrentContext();
```
According to the C-spec, `()` this implies that the declared function may take any number of arguments, which triggers a warning while compiling with `-Wstrict-prototypes`.

The correct way of declaring these functions would be using `(void)` instead:
```c
CIMGUI_API ImGuiContext* igGetCurrentContext(void);
```

**Comment by sonoro1234** [comment]
adding add_definitions("-Wstrict-prototypes") to CMakeLists gcc says:
```
cc1plus.exe: warning: command line option '-Wstrict-prototypes' is valid for C/ObjC but not for C++ [enabled by default]
```
And compiler must be C++ to be able to compile imgui.cpp.

I dont feel it is an issue as there are not derived consequences from this fact.

**Comment by sonoro1234** [comment]
Is this
https://github.com/sonoro1234/cimgui/tree/void_arg
enought?

**Comment by AlexAltea** [comment]
@sonoro1234 Yeah, that fixes the issue. Thanks a lot! :)
